
version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Server/Dockerfile
    ports:
    - "5000:5000"
    environment:
       MYSQL_HOST: '172.28.1.2'  # Use the service name as the hostname within the network
       MYSQL_PORT: "3306"
       MYSQL_USER: "root"
       MYSQL_PASSWORD: "pass1234"
       MYSQL_DATABASE: "Animal_Shelter"
    depends_on:
      - db
    networks:
      my_network:
        ipv4_address: 172.28.1.3

  db:
    image: nikole647/pythonproject3-db:latest
    environment:
      MYSQL_ROOT_PASSWORD: "pass1234"
    networks:
      my_network:
         ipv4_address: 172.28.1.2

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.1.0/24
